//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMerge.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMerge.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extract Diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return ResourceManager.GetString("Button_ExtractDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildCellBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Column Base Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildColumnBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Row Base Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildRowBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract diff with this row as column header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return ResourceManager.GetString("ContextMenu_DiffAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Column Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Row Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Column Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Row Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return ResourceManager.GetString("DefaultLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was added. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatAddedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatRemovedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultRowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return ResourceManager.GetString("GroupBox_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AddedColor {
            get {
                return ResourceManager.GetString("Label_AddedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Row Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_AddedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Rows({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_AddedRows {
            get {
                return ResourceManager.GetString("Label_AddedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CellHeight {
            get {
                return ResourceManager.GetString("Label_CellHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CellWidth {
            get {
                return ResourceManager.GetString("Label_CellWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Modified Row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return ResourceManager.GetString("Label_ColorModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Base Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_ColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return ResourceManager.GetString("Label_ColumnHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore File Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return ResourceManager.GetString("Label_IgnoreFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cell Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_LogFormat {
            get {
                return ResourceManager.GetString("Label_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cells({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return ResourceManager.GetString("Label_ModifiedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return ResourceManager.GetString("Label_ModifiedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Row Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return ResourceManager.GetString("Label_ModifiedRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Rows({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return ResourceManager.GetString("Label_ModifiedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return ResourceManager.GetString("Label_RemovedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Row Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_RemovedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Rows({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return ResourceManager.GetString("Label_RemovedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Base Log Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_RowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowColor {
            get {
                return ResourceManager.GetString("Label_RowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return ResourceManager.GetString("Label_RowHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Console {
            get {
                return ResourceManager.GetString("MenuItem_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff Extraction Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_DiffExtractionSetting {
            get {
                return ResourceManager.GetString("MenuItem_DiffExtractionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute external command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return ResourceManager.GetString("MenuItem_ExeExternalCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return ResourceManager.GetString("MenuItem_ExternalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return ResourceManager.GetString("MenuItem_FileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Src File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open src file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent File Sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return ResourceManager.GetString("MenuItem_RecentFileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart to apply the changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Reboot {
            get {
                return ResourceManager.GetString("Message_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting Diff ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return ResourceManager.GetString("Msg_ExtractingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return ResourceManager.GetString("Msg_OutofSheetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Files ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return ResourceManager.GetString("Msg_ReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not be displayed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return ResourceManager.GetString("Msg_Undisplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are too many records. Display only around diff. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return ResourceManager.GetString("Msg_WarnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return ResourceManager.GetString("RadioButton_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only Difference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return ResourceManager.GetString("RadioButton_ShowOnlyDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + I に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + L に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + O に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return ResourceManager.GetString("Shortcut_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return ResourceManager.GetString("Shortcut_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff Extraction Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_DiffSettingWindow {
            get {
                return ResourceManager.GetString("Title_DiffSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit External Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit File Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return ResourceManager.GetString("ToolTip_DstFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return ResourceManager.GetString("ToolTip_DstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return ResourceManager.GetString("ToolTip_SrcFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return ResourceManager.GetString("ToolTip_SrcSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap src and dst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return ResourceManager.GetString("ToolTip_Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Apply {
            get {
                return ResourceManager.GetString("Word_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Args に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Args {
            get {
                return ResourceManager.GetString("Word_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Blank {
            get {
                return ResourceManager.GetString("Word_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaseSensitive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return ResourceManager.GetString("Word_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return ResourceManager.GetString("Word_ColumnHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Default {
            get {
                return ResourceManager.GetString("Word_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Done {
            get {
                return ResourceManager.GetString("Word_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_DstFile {
            get {
                return ResourceManager.GetString("Word_DstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Edit {
            get {
                return ResourceManager.GetString("Word_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExactMatch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return ResourceManager.GetString("Word_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Executable {
            get {
                return ResourceManager.GetString("Word_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Font {
            get {
                return ResourceManager.GetString("Word_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Japanese {
            get {
                return ResourceManager.GetString("Word_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launguage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_MatchType {
            get {
                return ResourceManager.GetString("Word_MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Header Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return ResourceManager.GetString("Word_MaxRowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Path {
            get {
                return ResourceManager.GetString("Word_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Regex {
            get {
                return ResourceManager.GetString("Word_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Remove {
            get {
                return ResourceManager.GetString("Word_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Reset {
            get {
                return ResourceManager.GetString("Word_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return ResourceManager.GetString("Word_RowHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return ResourceManager.GetString("Word_RowHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Search {
            get {
                return ResourceManager.GetString("Word_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Setting {
            get {
                return ResourceManager.GetString("Word_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Sheet {
            get {
                return ResourceManager.GetString("Word_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return ResourceManager.GetString("Word_SheetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SheetName {
            get {
                return ResourceManager.GetString("Word_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SrcFile {
            get {
                return ResourceManager.GetString("Word_SrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set as Startup Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return ResourceManager.GetString("Word_StartupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Tool {
            get {
                return ResourceManager.GetString("Word_Tool", resourceCulture);
            }
        }
    }
}
