//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMerge.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMerge.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extract Diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return ResourceManager.GetString("Button_ExtractDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract diff with this row as header. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return ResourceManager.GetString("ContextMenu_DiffAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_FreezeColumn {
            get {
                return ResourceManager.GetString("ContextMenu_FreezeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ResetHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_SetHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfreeze column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_UnfreezeColumn {
            get {
                return ResourceManager.GetString("ContextMenu_UnfreezeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CellHeight {
            get {
                return ResourceManager.GetString("Label_CellHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CellWidth {
            get {
                return ResourceManager.GetString("Label_CellWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff Extraction Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_DiffExtractionSetting {
            get {
                return ResourceManager.GetString("MenuItem_DiffExtractionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute external command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return ResourceManager.GetString("MenuItem_ExeExternalCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return ResourceManager.GetString("MenuItem_ExternalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Src File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open dst File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open src file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent File Sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return ResourceManager.GetString("MenuItem_RecentFileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart to apply the changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Reboot {
            get {
                return ResourceManager.GetString("Message_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit External Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_CommandEditorWindow {
            get {
                return ResourceManager.GetString("Title_CommandEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_CommandsWindow {
            get {
                return ResourceManager.GetString("Title_CommandsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff Extraction Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_DiffSettingWindow {
            get {
                return ResourceManager.GetString("Title_DiffSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return ResourceManager.GetString("ToolTip_DstFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return ResourceManager.GetString("ToolTip_DstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return ResourceManager.GetString("ToolTip_SrcFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return ResourceManager.GetString("ToolTip_SrcSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap src and dst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return ResourceManager.GetString("ToolTip_Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Apply {
            get {
                return ResourceManager.GetString("Word_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Args に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Args {
            get {
                return ResourceManager.GetString("Word_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Default {
            get {
                return ResourceManager.GetString("Word_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Done {
            get {
                return ResourceManager.GetString("Word_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Edit {
            get {
                return ResourceManager.GetString("Word_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Executable {
            get {
                return ResourceManager.GetString("Word_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Japanese {
            get {
                return ResourceManager.GetString("Word_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launguage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Remove {
            get {
                return ResourceManager.GetString("Word_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Reset {
            get {
                return ResourceManager.GetString("Word_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Setting {
            get {
                return ResourceManager.GetString("Word_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Tool {
            get {
                return ResourceManager.GetString("Word_Tool", resourceCulture);
            }
        }
    }
}
